### ISSUE TITLE
Crypto code in the demo

### ISSUE THREAD

**Issue by rafalkrupinski** [aliev/aioauth-fastapi#13]
Hi and thank you for writing all this code!

There seems to be some generic crypto code in the fastapi demo. Is there a better way to do it, i.e. import it from some package?. At least some of it handles JWT, so perhaps pyjwt?

**Comment by rafalkrupinski** [comment]
it's only OAuth2 server implementation, not client, right?

**Comment by aliev** [comment]
Hi,

> Is there a better way to do it, i.e. import it from some package?

The demo project is not for production use; it is simply an example of how to use aioauth. I'm sure there is a better way to implement the crypto part of the project, but for demo purposes, I thought it was sufficient.

> it's only OAuth2 server implementation, not client, right?

Right, it's server implementation only. For the client, there is a nice authlib library that also supports asyncio.
